before:
  hooks:
    - go mod download
    - go mod tidy
builds:
  - id: pkr-darwin
    ldflags:
      - -s -w -X github.com/litencatt/pkr.Version={{.Version}} -X github.com/litencatt/pkr.commit={{.FullCommit}} -X github.com/litencatt/pkr.date={{.Date}} -X github.com/litencatt/pkr/version.Version={{.Version}}
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/pkr/main.go
archives:
  - id: pkr-archive
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format_overrides:
      - goos: darwin
        format: zip
    files:
      - CREDITS
      - README.md
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Version }}-next"
changelog:
  skip: true
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
brews:
  - name: pkr
    tap:
      owner: litencatt
      name: homebrew-tap
    commit_author:
      name: litencatt
      email: litencatt@gmail.com
    homepage: https://github.com/litencatt/pkr
    description: pkr is Poker CLI game.
    license: MIT
